# Generated by Django 5.1 on 2025-02-09 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="pen",
        ),
    ]
