# Generated by Django 5.1 on 2025-02-10 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_delete_pen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="Confirm_Password",
        ),
    ]
