# Generated by Django 5.1 on 2025-03-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_register_confirm_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="Confirm_Password",
            field=models.CharField(default="", editable=False, max_length=100),
        ),
    ]
