# Generated by Django 5.1 on 2025-03-08 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_register_confirm_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="Confirm_Password",
        ),
    ]
