# Generated by Django 5.1 on 2025-03-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_register_confirm_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="Email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
