# Generated by Django 5.1 on 2025-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_register_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="Email",
            field=models.EmailField(max_length=254),
        ),
    ]
