# Generated by Django 5.2 on 2025-04-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_login_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Password',
            new_name='password',
        ),
    ]
