# Generated by Django 5.1 on 2025-05-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_rename_email_login_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddTranscation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_t", models.CharField(max_length=200)),
                ("amount_t", models.FloatField()),
                ("category_t", models.CharField(max_length=10)),
                ("description_t", models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name="login",
            name="user",
        ),
        migrations.DeleteModel(
            name="register",
        ),
        migrations.DeleteModel(
            name="login",
        ),
    ]
