# Generated by Django 5.1 on 2025-05-27 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_addtranscation_remove_login_user_delete_register_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AddTranscation",
            new_name="Transcation",
        ),
    ]
