# Generated by Django 5.1 on 2025-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_rename_addtranscation_transcation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcation",
            name="category_t",
            field=models.CharField(max_length=100),
        ),
    ]
