# Generated by Django 5.1 on 2025-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_transcation_category_t"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcation",
            name="amount_t",
            field=models.IntegerField(),
        ),
    ]
