# Generated by Django 5.1 on 2025-06-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_transcation_amount_t"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcation",
            name="date_t",
            field=models.DateField(max_length=200),
        ),
    ]
